spring.application.name=Ecommerce
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:kalyani123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.h2.console.enabled=true
ecommerce.app.jwtSecret=${JWT_SECRET:ecommerceSecretKeyMustBeAtLeast64BytesLongForHS512AlgorithmAndMoreToEnsureSecurity12345}
ecommerce.app.jwtExpirationMs=86400000